name: Build and Deploy
on:
  push:
    branches:
      - master # or main, depending on your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14' # Specify your Node.js version
    - name: Install dependencies
      run: npm install
    - name: Build
      run: npm run build # Replace with your build command
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build # Replace with your build directory
